name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - '*'
  schedule:
    - cron: '0 0 * * *' # Nightly at 00:00 UTC

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
        include:
        - toolchain: x86_64-unknown-linux-gnu
          builder: ubuntu-latest
          os: linux
        - toolchain: x86_64-apple-darwin
          builder: macos-latest
          os: macos
        - toolchain: x86_64-pc-windows-msvc
          builder: windows-latest
          os: windows
        - toolchain: i686-pc-windows-msvc
          builder: windows-latest
          os: windows

    name: nightly - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.builder }}

    steps:
      - uses: actions/checkout@v2
      - name: Use latest nightly on scheduled builds
        if: github.event_name == 'schedule'
        run: echo "nightly" > rust-toolchain
      - run: rustup set default-host ${{ matrix.toolchain }}
      - run: rustup component add rust-src
      - run: rustc -vV
      - run: cargo build --verbose --all
      - run: cargo test --all
